### ISSUE TITLE
bug: crash, Subscript used on non-accessible variable when using Groupy software

### ISSUE THREAD

**Issue by samkatakouzinos** [gileli121/WindowTop#17] opened 2020-05-14 06:21 UTC
This occurs by opening and closing Windows Explorer. 

![WindowTop_WIq2IRbruA](https://user-images.githubusercontent.com/1305871/81899500-5516a280-95fe-11ea-9ae8-e6a3f56a7dc9.png)

System Info: 

OS Name	Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	****
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	To be filled by O.E.M.
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 3901 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F15, 23/10/2013
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	B75M-D3H
BaseBoard Version	x.x
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.18362.752"
Username	SKG-DV-002\samka_urshi1t
Time Zone	AUS Eastern Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	4.93 GB
Total Virtual Memory	31.9 GB
Available Virtual Memory	14.0 GB
Page File Space	16.0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualisation-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualisation Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by gileli121** [comment] 2020-06-02 20:25
Can you try please to run the program while Windows booted into safe mode and see if it still happens?

I suspect that the issue caused by some other program. 
If it will work on safe mode, it will tell that I am right and we continue to debug it from there.

Thanks.

**Comment by jakkaas** [comment] 2020-06-10 00:44
Same thing happening with me whlie switching apps using version 3.4.5. Not happening with Version 3.3.10
![image](https://user-images.githubusercontent.com/43289832/84214648-99a03b80-aae1-11ea-93c7-ad6dc8c2c5b7.png)
Thanks

**Comment by gileli121** [comment] 2020-06-10 06:31
@jakkaas The error message the same as in the original report?
You also see there "Line 5123" ?

**Comment by gileli121** [comment] 2020-06-11 12:46
Thanks for the report.
I will investigate why it happens and try to solve it.

**Comment by gileli121** [comment] 2020-07-03 18:17
I am investigating the issue using the pice of information you all gave that it line 5123.
Seems that you all have Groupy (https://www.stardock.com/products/groupy/) installed, I am right?

There was a fix in v3.3.8 for Groupy software
_**Fixed: compatibility issue with Groupy software that when the window is maximized, the arrow menu bar does not show
Fixed: compatibility issue with Groupy software with Shrink-Pro mode – when doing un-shrink on a tabbed window, the window loses the tab view
Fixed: compatibility issue with Groupy software with Shrink-Pro mode – when shrinking maximized window in a tab view, Groupy tabs still showing
Fixed: compatibility issue with Groupy software with Shrink-Pro mode – when shrinking & unshrinking window that viewed as tab, the window gets out of the tab list**_

The strange thing is that one of you said that with v3.3.10 it worked fine.
Maybe I did bad git merge.

I will try to see how v3.4.5 works when Groupy  installed

**Comment by gileli121** [comment] 2020-07-03 18:31
Update: 
I was right. I was able to reproduce the error with Groupy software.

**Steps to reproduce**
1. Groupy must be installed and running
2. Switch the monitor to another monitor

It does work with one monitor. 
But with 2 monitors there are issues.

I will work on a fix for this issue

**Comment by gileli121** [comment] 2020-07-03 18:58
So the steps I wrote were not the right steps.
The steps are:

1. Groupy must be installed and running
2. Open some window
3. Close the window

And indeed, it will work fine with v3.3.10 as users reported here

**Comment by gileli121** [comment] 2020-07-03 20:20
Issue fixed.
I will close the bug when the version with the fix will be released.

**Comment by samkatakouzinos** [comment] 2020-07-03 22:47
Yes I use Groupy.

**Comment by gileli121** [comment] 2020-07-03 22:52
I know. I was only needed to know the line number :) 

Please extract this file:
[WindowTop.zip](https://github.com/gileli121/WindowTop/files/4871785/WindowTop.zip)

Exit WindowTop if it is running and copy the WindowTop.exe to 
`C:\Program Files\WindowTop`
Delete the original `WindowTop.exe` and copy the new `WindowTop.exe` to there.

Please try this version and let me know if it works stable with Groupy

**Comment by gileli121** [comment] 2020-07-03 23:07
Something else got broken in the version I just sent you.
Don't try it yet.

**Comment by gileli121** [comment] 2020-07-04 16:40
[WindowTop v3.4.6-test.zip](https://github.com/gileli121/WindowTop/files/4873235/WindowTop.v3.4.6-test.zip)
Please try this file.
Put it instead of the file in `C:\Program Files\WindowTop` 

Please let me know how it works for you with Groupy

It includes also fix for bugs #31 , #30 , #29

**Comment by samkatakouzinos** [comment] 2020-07-05 04:30
It goes well so far. No notifications. No silent exits.
Keeping the old version name in the test software threw me a little but no biggie.

**Comment by gileli121** [comment] 2020-07-05 05:55
Great to hear!
I did not understand your last sentence - `Keeping the old version name in the test software threw me a little but no biggie.`

**Comment by samkatakouzinos** [comment] 2020-07-05 06:32
When I was running the new version and visited 'About WindowTop …' it showed v3.4.5.
Thought it might have had the word 'test' or similar in there.

**Comment by gileli121** [comment] 2020-07-05 06:35
Yes, I did not update the version number in the code.
Ignore it.

When I will release the new version, it will show another version number.

I will close this issue when I will release the new version.

**Comment by jakkaas** [comment] 2020-07-05 13:35
Everything Working fine, even in Groupy except disabling the toolbar menu over windows, disables shortcut key.

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 5, 2020 at 12:05 PM, Gil Eliyahu<notifications@github.com> wrote:   


Yes, I did not update the version number in the code.
Ignore it.

When I will release the new version, it will show another version number.

I will close this issue when I will release the new version.

**Comment by gileli121** [comment] 2020-07-05 14:47
Thanks @jakkaas for this report!
This is a big issue and it happens also in v3.4.5 
I opened issue #32

**Comment by gileli121** [comment] 2020-07-05 16:26
@jakkaas 
Please try this file and let me know if fixed for you.
[WindowTop - fix2.zip](https://github.com/gileli121/WindowTop/files/4875255/WindowTop.-.fix2.zip)

**Comment by jakkaas** [comment] 2020-07-05 21:43
Yes Issue has been fixed. Thanks

Sent from Yahoo Mail on Android 
 
  On Sun, Jul 5, 2020 at 9:57 PM, Gil Eliyahu<notifications@github.com> wrote:   


@jakkaas
Please try this file and let me know if fixed for you.
WindowTop - fix2.zip

**Comment by gileli121** [comment] 2020-07-06 21:40
Released in v3.4.6

**Comment by gileli121** [comment] 2021-03-18 07:02
Reopened.
This bug is back in v5 that rewritten in C#

**Comment by gileli121** [comment] 2021-03-26 18:50
Fixed in v5 (Not released yet)

**Comment by gileli121** [comment] 2021-03-27 20:18
Released in v5.1.6

**Closed by gileli121** 2021-03-27 20:18 UTC
Labels: bug, fixed, high-priority
