### ISSUE TITLE
Make WindowTop run as Admin to allow controlling also "Admin" windows

### ISSUE THREAD

**Issue by boydfields** [gileli121/WindowTop#70] opened 2021-04-02 04:50 UTC
5.1.9 installs version 5.1.8.
Would like to try it as having issues with the app crashing when run as admin via task scheduler.
Thanks
Boyd

**Comment by gileli121** [comment] 2021-04-02 08:40
Thanks for the report.
Why you run the app via task scheduler?

**Comment by gileli121** [comment] 2021-04-02 08:53
I fixed the issue that the installer installed v5.1.8
Download again.
Thanks for the report

**Comment by boydfields** [comment] 2021-04-02 12:45
You're welcome.

I use a few apps which start upon logon and require admin rights.  Tasks can elevate a process without the UAC prompt.  I need to run WindowsTop as admin so it can interact with other elevated processes.  It would be annoying to accept a UAC prompt every time I logon.  

However, doing so seems to cause your app to crash several times.  I'm retesting now.

Many thanks
Boyd

**Comment by gileli121** [comment] 2021-04-02 20:12
I think that I should make it work as admin by default and fix any issues about it.
Are you sure that it is related to the fact that you run it as admin?

**Comment by boydfields** [comment] 2021-04-03 00:36
It would make sense as it covers both bases (low integrity/high integrity process execution).
Apologies, I have yet to try again with WindowTop as have had a busy day. I'll play around with it tomorrow and report back :)
Many thanks
Boyd

**Comment by gileli121** [comment] 2021-04-07 19:48
It will done for the installer version

**Comment by Vstory** [comment] 2021-04-07 23:20
The current WindowTop cannot top the applications started by the administrator.
😇

**Comment by Vstory** [comment] 2021-04-20 15:38
> It will done for the installer version

Can this feature be developed first? I really need it.

**Comment by gileli121** [comment] 2021-04-20 18:04
Everything under tag `planed-for-v5.(X+1).Y` will be in v5.3 that is the next features update.
Currently I am no longer working on bugfixes and working on v5.3 so I will work on this request soon

**Comment by gileli121** [comment] 2021-04-23 14:04
Hello @Vstory , @boydfields 
Please let me know how this version works for you:
[WindowTop 5.2.6 - Portable.zip](https://github.com/gileli121/WindowTop/files/6365815/WindowTop.5.2.6.-.Portable.zip)
[WindowTop 5.2.6 - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6365816/WindowTop.5.2.6.-.setup.exe.zip)

If it works well, let me know!
Thanks!

**Comment by Vstory** [comment] 2021-04-23 15:08
> [WindowTop 5.2.6 - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6365816/WindowTop.5.2.6.-.setup.exe.zip)

It has been tested, and the window with administrator authority can be topped normally.

**Comment by gileli121** [comment] 2021-04-23 16:29
Thanks
`A command line window will flash every time it starts, which is very annoying.`
Can you send recording of it? You can use: https://www.screentogif.com/ 
To record and send here gif that shows the issue

**Comment by Vstory** [comment] 2021-04-23 16:55
> Thanks
> `A command line window will flash every time it starts, which is very annoying.`
> Can you send recording of it? You can use: https://www.screentogif.com/
> To record and send here gif that shows the issue

After starting the application, a command line pop-up window will flash.
[bandicam 2021-04-24 00-49-59-944.zip](https://github.com/gileli121/WindowTop/files/6366899/bandicam.2021-04-24.00-49-59-944.zip)

**Comment by gileli121** [comment] 2021-04-23 18:04
@Vstory  thanks for the report.
I could not reproduce it on my computer but I think I know why it happned.
Please try this build:
[WindowTop 5.2.6 - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6367267/WindowTop.5.2.6.-.setup.exe.zip)
Let me know if it fixed

**Comment by Vstory** [comment] 2021-04-24 06:04
> Please try this build:
> [WindowTop 5.2.6 - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6367267/WindowTop.5.2.6.-.setup.exe.zip)
> Let me know if it fixed

It has been fixed.

**Comment by boydfields** [comment] 2021-04-25 00:40
Hello Gil,

My use case is somewhat different from the typical user.  I often run apps,
such as the command prompt or powershell console, as different user
accounts.
For example, I may have three command prompt windows open with the 1st
being my own user account; the 2nd as SYSTEM account; and 3rd
TrustedInstaller account.
Based on how you've set up the task for WindowTop to run, it can only
interact with windows which run under the current user account.
I have tweaked the settings to allow WindowTop to run interactively as the
SYSTEM account, using PSEXEC from Sysinternals.
Attached are screenshots showing my settings. These now permit me to use
WindowTop on any window regardless of permissions.

Boyd Fields
boydfields.com
M:07747846066

**Comment by gileli121** [comment] 2021-04-25 04:23
@boydfields 
Currently to set WindowTop to run on startup as Admin I use this command:
```
schtasks /create /sc onlogon /tn "Run WindowTop as Admin on startup" /tr "C:\Program Files\WindowTop\WindowTop.exe" /rl highest /f
```

Can you modify this command so it will cover also your use case?
I did not got any screenshots

**Comment by Vstory** [comment] 2021-04-25 14:57
> Please try this build:
> [WindowTop 5.2.6 - setup.exe.zip](https://github.com/gileli121/WindowTop/files/6367267/WindowTop.5.2.6.-.setup.exe.zip)
> Let me know if it fixed

I am experiencing some crashes, are these logs helpful?
[WindowTop.zip](https://github.com/gileli121/WindowTop/files/6372224/WindowTop.zip)

**Comment by gileli121** [comment] 2021-04-25 15:22
@Vstory 
Thanks for the report.
No, these logs not helping me.

But there is a way to get helpful logs.
Please create NLog.config file with the following content:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      internalLogLevel="Info">
	  
  <targets>
    <target name="logFile" xsi:type="File"
            fileName="${specialfolder:folder=ApplicationData}/WindowTop/WindowTopLog.log"
            layout="${logger}(${level:uppercase=true}): ${message}"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="logFile" />
  </rules>
</nlog>
```

And put it in the installation folder:
![image](https://user-images.githubusercontent.com/17680514/115998995-a2630880-a5f2-11eb-9dc0-514e7f352869.png)

Next, exit WindowTop and start it again.

The log file will be created under 
![image](https://user-images.githubusercontent.com/17680514/115999026-c4f52180-a5f2-11eb-8228-034eff2d06cc.png)
![image](https://user-images.githubusercontent.com/17680514/115999040-de966900-a5f2-11eb-9840-e3e50be33fe3.png)


To view it, just open it with text editor (you can drag the file to notepad)
The content should be something like this:
![image](https://user-images.githubusercontent.com/17680514/115999092-13a2bb80-a5f3-11eb-8215-50bb215e8ff6.png)


Wait for any crashes and when you have multiple crashes, please send this file here.
Thanks!

**Comment by boydfields** [comment] 2021-04-27 13:28
Hello Gil,

Many apologies in the delay getting back to you.

Your command is fine for processes which operate in the elevated user’s context. It will not work however should a process be running in a context above standard admin rights, such as SYSTEM or TrustedInstaller.

I’m sure it’s possible to modify your applications code but I’m not a programmer so cannot recommend such a method.  The only thing I can do is recommend using PSEXEC which is part of Sysinternals (a Microsoft package of tools).  The screenshots I sent show how I adapted your task schedule to use them.  Do you have another email account I could send them to you?

In addition, there does seem to be an issue with ‘dark mode’ when WindowTop is running as SYSTEM.  It simply does not work on any window.  Other apps I’ve tried are able to do all the above without issue, but I wouldn’t know how they manage it as I’m not a coder.  Sorry for not being more helpful.

Boyd

**Comment by gileli121** [comment] 2021-04-27 23:59
@boydfields 
On second thought, I don't think that I should modify the software to run as system/TrustedInstaller because I don't think that it worth it.. most programs run maximum with Admin privileges and not more. Even task manager running as Admin and not as system/TrustedInstaller.

I don't see that it worth doing it. especially if you said that dark-mode not working when the program running in system privileges.

Any realworld examples of apps that need more than admin privileges?

**Comment by gileli121** [comment] 2021-04-28 00:00
@Vstory 
Any updates about crashes/logs?

**Comment by boydfields** [comment] 2021-04-28 05:06
No, I completely agree with you. Mine is a special use case but thought it worth mentioning. Not being a coder I wouldn’t know how easy or difficult it would be. Your assessment of the “issue” is correct and not worth exploring more. Thanks for letting me know. 

On 28 Apr 2021, at 00:59, Gil Eliyahu ***@***.***> wrote:

﻿
@boydfields
On second thought, I don't think that I should modify the software to run as system/TrustedInstaller because I don't think that it worth it.. most programs run maximum with Admin privileges and not more. Even task manager running as Admin and not as system/TrustedInstaller.

I don't see that it worth doing it. especially if you said that dark-mode not working when the program running in system privileges.

Any realworld examples of apps that need more than admin privileges?

**Comment by gileli121** [comment] 2021-04-28 18:04
@boydfields / @Vstory 
Other than that this version works stable?

**Comment by Vstory** [comment] 2021-04-28 18:09
> @Vstory
> Any updates about crashes/logs?

The problem did not recur.

**Comment by Vstory** [comment] 2021-04-28 18:10
> @boydfields / @Vstory
> Other than that this version works stable?

I think this version is stable.I currently use it normally.

**Comment by gileli121** [comment] 2021-04-28 18:16
Great!
Thanks

**Comment by Vstory** [comment] 2021-04-28 18:22
> Great!
> Thanks

Can you support providing an option in the portable version to automatically create a task schedule so that it can be started automatically after booting.

Of course, this is just more convenient.  Currently, I created it myself.

**Comment by gileli121** [comment] 2021-04-28 18:26
I prefer not because some users may create the task and then remove the program and you end up with a mess on the system (that you have a task that tries to start executable that not available)
I prefer to avoid it

**Comment by Vstory** [comment] 2021-04-28 19:28
😷

**Closed** 2021-05-03 20:15 UTC
Labels: done, enhancement, planed-for-v5.(X+1).Y
